
version: "3.0"
services:
  rails:
    build: .
    command: bundle exec foreman start -f Procfile_development
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      PGHOST: postgres
      PGUSER: postgres
    env_file:
    - docker.env
    ports:
      - 3001:3001
    volumes:
      - ./:/src

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_MULTIPLE_DATABASES: bikeindex_development, bikeindex_test
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    ports:
      - 6379:6379

volumes:
  postgres_data: {}
